import type { NextPage } from 'next';
import { useRef } from 'react';

import Head from 'next/head';

import { ChipsFilter } from '../../src/components/molecules/chips-filter';
import { HeadlineSupermarket } from '../../src/components/molecules/headline';
import { LineBar } from '../../src/components/molecules/line-bar';
import { SearchBox } from '../../src/components/molecules/SearchBox';
import { SupermarketContent } from './components/supermarket-content';

import styles from '@Application/pages/home/index.module.scss';

// import { ProductService } from '../../../Infrastructure/Services/ProductService';

const Home: NextPage = () => {
  const filterSupermarkets = useRef( [
    {
      name: 'Tottus',
      active: false
    },
    {
      name: 'Lider',
      active: false
    },
    {
      name: 'Jumbo',
      active: false
    },
    {
      name: 'Santa Isabel',
      active: false
    }
  ] );
  const productProps = {
    name: 'Product Name',
    description: 'Product description very long for testing purposes',
    unit: 'Kg',
    price: '$100',
    image: 'https://picsum.photos/200/300',
    source: 'https://dummyimage.com/400x600/000/fff&text=ProductImage'
  };

  const handleSubmit = async ( evt: any ) => {
    evt.preventDefault();
  };

  return (
    <div className={`${ styles.container }`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${ styles.main }`}>

        <header className={`${ styles.main__header }`}>
          <LineBar />
        </header>

        <article className={`${ styles.content }`}>

          <header className={`${ styles.content__header }`}>
            <div className={`${ styles[ 'content__search-box' ] }`}>
              <SearchBox handleSubmit={handleSubmit} placeholder={'Encuentra la mejor opción...'} />
            </div>
            <div className={`${ styles.content__chips }`}>
              <ChipsFilter itemsRef={filterSupermarkets} />
            </div>
          </header>

          <article className={`${ styles.content__supermarkets }`}>
            {/* <SupermarketContent items={new Array( 8 ).fill( productProps )} type={HeadlineSupermarket.Jumbo} /> */}
          </article>

        </article>

      </main>

    </div>
  );
};

export default Home;
