import type { GetServerSideProps, NextPage } from 'next';
import { useRef, useState } from 'react';

import Head from 'next/head';

import { ChipsFilter } from '../../src/components/molecules/chips-filter';
import { HeadlineSupermarket } from '../../src/components/molecules/headline';
import { LineBar } from '../../src/components/molecules/line-bar';
import { SearchBox } from '../../src/components/molecules/search-box';
import { SupermarketContent } from './components/supermarket-content';

import { useLoading } from '../../src/hooks/use-loading';

import { findProducts } from '../../src/services/supermarket/products/find-products';
import { formatProducts } from '../../src/services/supermarket/products/format-products';

import styles from './index.module.scss';

const Home: NextPage = () => {
  const { setLoading } = useLoading();
  const filterSupermarkets = useRef( [
    {
      name: 'Lider',
      active: true
    },
    {
      name: 'Jumbo',
      active: true
    }
  ] );

  const [ items, setItems ] = useState<any>( [] );

  const handleSubmit = async ( evt: any ) => {
    evt.preventDefault();
    const toSearch = evt.target[ 'search-input' ].value;
    const supermarketsToSearch = filterSupermarkets.current.filter( s => s.active );
    const supermarketNames = supermarketsToSearch.map( s => s.name );

    if ( toSearch.trim() === '' ) return;

    setLoading( true );
    const data = await findProducts( toSearch, supermarketNames );
    setItems( formatProducts( data[ 0 ] ) );
    setLoading( false );
  };

  return (
    <div className={`${ styles.container }`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${ styles.main }`}>

        <header className={`${ styles.main__header }`}>
          <LineBar />
        </header>

        <article className={`${ styles.content }`}>

          <header className={`${ styles.content__header }`}>
            <div className={`${ styles[ 'content__search-box' ] }`}>
              <SearchBox handleSubmit={handleSubmit} placeholder={'Encuentra la mejor opción...'} />
            </div>
            <div className={`${ styles.content__chips }`}>
              <ChipsFilter itemsRef={filterSupermarkets} />
            </div>
          </header>

          <article className={`${ styles.content__supermarkets }`}>
            <SupermarketContent items={items} type={HeadlineSupermarket.Lider} />
          </article>

          {/* <article className={`${ styles.content__supermarkets }`}>
            <SupermarketContent items={[]} type={HeadlineSupermarket.Jumbo} />
          </article> */}

        </article>

      </main>

    </div>
  );
};

export default Home;
